name: Publish

permissions:
    contents: write

on:
    workflow_dispatch:

jobs:
    publish:
        runs-on: windows-latest
        steps:
            - run: npm install
            - run: npm run publish
